### ISSUE TITLE
Upgrade to Akka 2.8.x & Scala 3

### ISSUE THREAD

**Issue by jdorleans** [altoo-ag/akka-kryo-serialization#291]
Would there be any plans of upgrading to the lastest versions of akka?

**Comment by dwickern** [comment]
> Is there anything specific that is not working with Akka 2.8?

On Akka 2.9.5 / Scala 3, an error occurs on startup:
```
java.lang.NoSuchMethodError: 'void akka.serialization.Serializer.$init$(akka.serialization.Serializer)'
	at io.altoo.akka.serialization.kryo.KryoSerializer.<init>(KryoSerializer.scala:81)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor$$anonfun$1(ReflectiveDynamicAccess.scala:40)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:44)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor$$anonfun$2(ReflectiveDynamicAccess.scala:48)
	at scala.util.Success.flatMap(Try.scala:258)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:48)
	at akka.serialization.Serialization.serializerOf(Serialization.scala:390)
	at akka.serialization.Serialization.$anonfun$2(Serialization.scala:458)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.immutable.HashMapBuilder.addAll(HashMap.scala:2406)
	at scala.collection.immutable.HashMap$.from(HashMap.scala:2218)
	at scala.collection.immutable.HashMap$.from(HashMap.scala:2194)
	at scala.collection.MapOps$WithFilter.map(Map.scala:381)
	at akka.serialization.Serialization.<init>(Serialization.scala:458)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
	at akka.serialization.SerializationExtension$.createExtension(SerializationExtension.scala:18)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1201)
	at akka.actor.ActorSystemImpl.loadExtensions$1$$anonfun$1(ActorSystem.scala:1244)
	at scala.collection.immutable.Vector.foreach(Vector.scala:2124)
	at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1253)
	at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1257)
	at akka.actor.ActorSystemImpl.liftedTree3$1(ActorSystem.scala:1078)
	at akka.actor.ActorSystemImpl._start$lzyINIT1(ActorSystem.scala:1086)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1065)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1088)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:274)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:318)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:292)
```

**Comment by cptwunderlich** [comment]
We're affected by this too, @dwickern have you found a workaround?

**Comment by He-Pin** [comment]
Akka will provide commercial support for this.
